---

- name: Create PiHole base directory in /opt
  become: true
  file:
    path: /opt/pihole
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create PiHole configuration directory for /etc/pihole
  become: true
  file:
    path: /opt/pihole/etc-pihole
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create PiHole configuration directory for /etc/dnsmasq.d
  become: true
  file:
    path: /opt/pihole/etc-dnsmasq_d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create PiHole image creation directory
  become: true
  file:
    path: /opt/pihole/img_build
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Dockerfile
  become: true
  copy:
    src: 'files/Dockerfile'
    dest: '/opt/pihole/img_build/Dockerfile'
    owner: root
    group: root
    mode: '0644'

- name: Copy Patchfile
  become: true
  copy:
    src: 'files/dont-reset-password-on-boot.patch'
    dest: '/opt/pihole/img_build/dont-reset-password-on-boot.patch'
    owner: root
    group: root
    mode: '0644'

- name: Copy Unbound config file
  become: true
  copy:
    src: 'files/pi-hole.conf'
    dest: '/opt/pihole/img_build/pi-hole.conf'
    owner: root
    group: root
    mode: '0644'

- name: Copy Unbound s6 init script
  become: true
  copy:
    src: 'files/unbound-run'
    dest: '/opt/pihole/img_build/unbound-run'
    owner: root
    group: root
    mode: '0644'

