---
- name: Create group for pihole container
  become: true
  group:
    name: pihole
    system: true

- name: Create user for pihole container
  become: true
  user:
    create_home: false
    name: pihole
    group: pihole
    system: true

- name: Create PiHole base directory in /opt
  become: true
  file:
    path: /opt/pihole
    state: directory
    owner: pihole
    group: pihole

- name: Create PiHole configuration directory for /etc/pihole
  become: true
  file:
    path: /opt/pihole/etc-pihole
    state: directory
    owner: pihole
    group: pihole
    mode: '0755'

- name: Create PiHole configuration directory for /etc/dnsmasq.d
  become: true
  file:
    path: /opt/pihole/etc-dnsmasq_d
    state: directory
    owner: pihole
    group: pihole
    mode: '0755'

- name: Create PiHole image creation directory
  become: true
  file:
    path: /opt/pihole/img_build
    state: directory
    owner: pihole
    group: pihole
    mode: '0755'

- name: Copy Dockerfile
  become: true
  copy:
    src: 'files/Dockerfile'
    dest: '/opt/pihole/img_build/Dockerfile'
    owner: pihole
    group: pihole
    mode: '0644'

- name: Copy Patchfile
  become: true
  copy:
    src: 'files/dont-reset-password-on-boot.patch'
    dest: '/opt/pihole/img_build/dont-reset-password-on-boot.patch'
    owner: pihole
    group: pihole
    mode: '0644'
