---
- name: Pull pihole/pihole:latest
  community.docker.docker_image:
    name: pihole/pihole:latest
    source: pull

- name: Create Modified Runtime Image
  community.docker.docker_image:
    source: build
    build:
      path: /opt/pihole/img_build
    name: localhost:5000/panamax-pihole
    tag: latest
  notify:
    - Restart PiHole

- name: Add service updater script
  become: true
  copy:
    src: 'files/updater.sh'
    dest: '/opt/pihole/updater.sh'
    owner: root
    group: root
    mode: '0755'

