---

- name: Install Service Unit file
  become: true
  copy:
    src: 'files/pihole.service'
    dest: "/etc/systemd/system/pihole.service"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart PiHole

- name: Enable the Service Unit file
  become: true
  systemd:
    state: started
    enabled: true
    name: pihole.service

